### PR TITLE
Initial upload of data files needed for the RecoTracker/LSTCore CMSSW package

### PR DESCRIPTION
**Pull request by VourMa**
This PR includes the needed data files for the newly proposed RecoTracker/LSTCore CMSSW pakage to run.

@slava77 @ariostas

### CODE REVIEW

**Comment by slava77** [comment]
to avoid constant interference from unrelated commit merges in the PR tests of https://github.com/cms-sw/cmssw/pull/45117, perhaps this PR can be merged already?

Otherwise the presence of this data PR in the dependency of https://github.com/cms-sw/cmssw/pull/45117 triggers the bot to include everything between the last IB and the head of cmsdist and cms-sw master.

**Comment by mandrenguyen** [comment]
+1

**Comment by slava77** [comment]
@smuzaffar 
now that reco has signed off, perhaps this PR can be signed by externals and merged?

**Comment by smuzaffar** [comment]
+externals

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cms-sw/orp-l2 

to avoid constant interference from unrelated commit merges in the PR tests of https://github.com/cms-sw/cmssw/pull/45117, perhaps this PR can be merged already?

Otherwise the presence of this data PR in the dependency of https://github.com/cms-sw/cmssw/pull/45117 triggers the bot to include everything between the last IB and the head of cmsdist and cms-sw master.

**Comment by slava77** [comment]
@antoniovilela, @sextonkennedy, @rappoccio 

> 
> to avoid constant interference from unrelated commit merges in the PR tests of [cms-sw/cmssw#45117](https://github.com/cms-sw/cmssw/pull/45117), perhaps this PR can be merged already?
> 
> Otherwise the presence of this data PR in the dependency of [cms-sw/cmssw#45117](https://github.com/cms-sw/cmssw/pull/45117) triggers the bot to include everything between the last IB and the head of cmsdist and cms-sw master.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
